version: '3.8'

services:
  app_dev:
    image: images_optimizer_api:v1
    container_name: images_optimizer_api_dev
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    env_file: .env
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - api_nestjs

networks:
  api_nestjs:
    driver: bridge
